version: '3'

services:
  web:
    build: .
    container_name: fsinfo-poll-backend
    image: fsinfo-poll
    depends_on:
      - mongo
    environment:
      - MONGO_PASSWORD=fjseid119sa74
      - MONGO_USERNAME=root
      - MONGO_URL=mongo:27017
    ports:
      - "127.0.0.1:8000:8000"

  mongo:
    image: mongo
    container_name: mongo-database
    restart: always
    volumes:
      - mongo-db-volume:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: fjseid119sa74

  mongo-express:
    image: mongo-express
    container_name: mongo-admin-ui
    restart: always
    ports:
      - "0.0.0.0:7231:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:fjseid119sa74@mongo:27017/

volumes:
  mongo-db-volume: